---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: policies
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./policies
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: none

